### ISSUE TITLE
【第6章】修正箇所提案

### ISSUE THREAD

**Issue by wakamii** [good-faith-collaboration-ja/good-faith-collaboration-ja.github.io#9]
池谷のもとで学ばせていただいているものです。
今回は修正箇所の提案で投稿させていただきます。

¶24 20 Sometimes his Wikipedia edits are challenged, as we will see, and statistics on his contributions and “edit count” have been a topic of discussion.

提案訳
私たちが見てきたように、彼のウィキペディアの編集は時に批判にさらされ、彼の寄稿と「編集回数」の統計は議論の対象となる。

この文章の訳が抜けてしまっているように思います。どうぞご検討ください。

**Comment by whym** [comment]
見落としてしまっていたようです。ありがとうございました。
